require:
  - rubocop-minitest
  - rubocop/cop/custom

AllCops:
  CacheRootDirectory: 'vendor'
  NewCops: enable
  SuggestExtensions: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/MapToHash:
  Enabled: false

Custom/IpRanges:
  Enabled: true
