require_relative 'legitbot/legitbot'
require_relative 'legitbot/botmatch'

require_relative 'legitbot/apple'
require_relative 'legitbot/baidu'
require_relative 'legitbot/bing'
require_relative 'legitbot/duckduckgo'
require_relative 'legitbot/facebook'
require_relative 'legitbot/google'
require_relative 'legitbot/yandex'
