name: Autocorrect

on:
  schedule:
    - cron: "29 6 * * 6"

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
      - name: Run linter
        run: bundle exec rubocop -A
        continue-on-error: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update/lint-autocorrect
          delete-branch: true
          commit-message: "🔧 autocorrect by Rubocop"
          title: "[rubocop] Automatic corrections"
          body: |
            Please review automatic changes proposed by `rubocop -a`.
