name: autocorrect

on:
  schedule:
  - cron: '29 6 * * 6'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ 3.0 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ruby }}-gems-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run tests
      run: bundle exec rake test
    - name: Run linter
      run: bundle exec rubocop --auto-correct
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: update/lint-autocorrect
        delete-branch: true
        commit-message: '🔧 autocorrect by Rubocop'
        title: '[rubocop] Automatic corrections'
        body: |
          Please review automatic changes proposed by `rubocop -a`.
