name: PR Checks

on:
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    permissions: {}

    strategy:
      fail-fast: false
      matrix:
        ruby: [jruby, 3.2, 3.3, 3.4, 4.0]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # 1.307.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test

  lint:
    name: Lint
    needs: test
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # v1.307.0
        with:
          bundler-cache: true
      - name: Run linter
        run: bundle exec rubocop

  gha-security:
    name: GitHub Actions Security Analysis
    needs: test
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b572f7b1a1c2d41efaab43d504f68d215c3cd727 # v0.5.4
