name: release

on:
  push:
    branches:
      - master
    paths:
      - "lib/legitbot/version.rb"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
      - name: Publish
        uses: rubygems/release-gem@v1
