name: Release

on:
  push:
    branches:
      - master
    paths:
      - "lib/legitbot/version.rb"

jobs:
  release:
    name: Publish to Rubygems
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # 1.307.0
        with:
          bundler-cache: false
      - name: Run tests
        run: bundle exec rake test
      - name: Publish
        uses: rubygems/release-gem@6317d8d1f7e28c24d28f6eff169ea854948bd9f7 # 1.2.0
